-- Grants of the API database user (password not included: create the user yourself first).
-- CREATE USER "blast_api"@"localhost" IDENTIFIED BY "...";
GRANT SELECT ON `wagodb`.`amyl_ergebnis` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`blast_seq_ncbi` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`blast_api_key` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`blast_taxon` TO `blast_api`@`localhost`;
GRANT SELECT, INSERT ON `wagodb`.`blast_job` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`blast_ram_status` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`amyl_lauf` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`blast_import` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`blast_acc` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`amyl_sequenz` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`blast_seq_herkunft` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`blast_ram_mess` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`amyl_kandidat` TO `blast_api`@`localhost`;
GRANT SELECT, INSERT, UPDATE ON `wagodb`.`blast_api_hits` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`blast_seq` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`blast_acc_herkunft` TO `blast_api`@`localhost`;
GRANT SELECT, INSERT ON `wagodb`.`amyl_job` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`amyl_fenster` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`blast_release` TO `blast_api`@`localhost`;
GRANT SELECT ON `wagodb`.`blast_job_hit` TO `blast_api`@`localhost`;
